"""add gem detail columns to game_mechanic

Revision ID: 1c6c9a9614bb
Revises: 8cdd9188c489
Create Date: 2026-05-23 01:17:13.426467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c6c9a9614bb'
down_revision: Union[str, Sequence[str], None] = '8cdd9188c489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_mechanic', sa.Column('base_type_name', sa.String(length=256), nullable=True))
    op.add_column('game_mechanic', sa.Column('gem_type', sa.String(length=32), nullable=True))
    op.add_column('game_mechanic', sa.Column('gem_tier', sa.Integer(), nullable=True))
    op.add_column('game_mechanic', sa.Column('max_level', sa.Integer(), nullable=True))
    op.add_column('game_mechanic', sa.Column('variant_id', sa.String(length=128), nullable=True))
    op.add_column('game_mechanic', sa.Column('granted_effect_id', sa.String(length=128), nullable=True))
    op.add_column('game_mechanic', sa.Column('gem_tags_string', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_mechanic', 'gem_tags_string')
    op.drop_column('game_mechanic', 'granted_effect_id')
    op.drop_column('game_mechanic', 'variant_id')
    op.drop_column('game_mechanic', 'max_level')
    op.drop_column('game_mechanic', 'gem_tier')
    op.drop_column('game_mechanic', 'gem_type')
    op.drop_column('game_mechanic', 'base_type_name')
    # ### end Alembic commands ###
