"""add_weapon_attr_requirements_to_game_mechanic

Revision ID: 1e0e137c9b51
Revises: 6e8ba0e734da
Create Date: 2026-05-22 20:28:48.772395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e0e137c9b51'
down_revision: Union[str, Sequence[str], None] = '6e8ba0e734da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_mechanic', sa.Column('weapon_requirements', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('game_mechanic', sa.Column('attribute_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('game_mechanic', sa.Column('required_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_mechanic', 'required_level')
    op.drop_column('game_mechanic', 'attribute_requirements')
    op.drop_column('game_mechanic', 'weapon_requirements')
    # ### end Alembic commands ###
