"""initial_schema

Revision ID: 6e8ba0e734da
Revises: 
Create Date: 2026-05-22 01:12:06.454015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e8ba0e734da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('build_meta',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('league_version', sa.String(length=32), nullable=False),
    sa.Column('power_rating', sa.Float(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('damage_types', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('playstyle', sa.String(length=64), nullable=True),
    sa.Column('estimated_budget_divines', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_build_meta_character_id'), 'build_meta', ['character_id'], unique=True)
    op.create_table('character',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_name', sa.String(length=128), nullable=False),
    sa.Column('character_name', sa.String(length=128), nullable=False),
    sa.Column('league', sa.String(length=64), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('char_class', sa.String(length=32), nullable=False),
    sa.Column('ascendancy', sa.String(length=32), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_account_name'), 'character', ['account_name'], unique=False)
    op.create_index(op.f('ix_character_character_name'), 'character', ['character_name'], unique=False)
    op.create_index(op.f('ix_character_league'), 'character', ['league'], unique=False)
    op.create_table('equipment_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('slot', sa.String(length=32), nullable=False),
    sa.Column('item_name', sa.String(length=256), nullable=False),
    sa.Column('base_type', sa.String(length=128), nullable=False),
    sa.Column('rarity', sa.String(length=16), nullable=False),
    sa.Column('explicit_mods', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('implicit_mods', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('crafted_mods', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('enchant_mods', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('sockets', sa.Integer(), nullable=False),
    sa.Column('links', sa.Integer(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_item_character_id'), 'equipment_item', ['character_id'], unique=False)
    op.create_table('game_mechanic',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.String(length=128), nullable=False),
    sa.Column('skill_name', sa.String(length=256), nullable=False),
    sa.Column('skill_type', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=4096), nullable=True),
    sa.Column('damage_formula', sa.String(length=1024), nullable=True),
    sa.Column('base_crit_chance', sa.Float(), nullable=True),
    sa.Column('damage_effectiveness', sa.Float(), nullable=True),
    sa.Column('trigger_conditions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('synergies', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('game_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_mechanic_skill_id'), 'game_mechanic', ['skill_id'], unique=True)
    op.create_table('generated_build',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('build_name', sa.String(length=256), nullable=False),
    sa.Column('user_request', sa.String(length=1024), nullable=True),
    sa.Column('core_skill', sa.String(length=128), nullable=False),
    sa.Column('damage_types', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('reasoning_chain', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('estimated_cost_min', sa.Float(), nullable=True),
    sa.Column('estimated_cost_max', sa.Float(), nullable=True),
    sa.Column('skill_gems', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('passive_tree', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('equipment', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_passed', sa.Boolean(), nullable=True),
    sa.Column('validation_errors', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('model_used', sa.String(length=64), nullable=False),
    sa.Column('game_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passive_tree',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('node_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('keystone_nodes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('mastery_choices', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ascendancy_nodes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('bandit_choice', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passive_tree_character_id'), 'passive_tree', ['character_id'], unique=True)
    op.create_table('skill_group',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('active_skill_id', sa.String(length=128), nullable=False),
    sa.Column('active_skill_name', sa.String(length=256), nullable=True),
    sa.Column('support_gems', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('trigger_condition', sa.String(length=512), nullable=True),
    sa.Column('gem_links', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_group_character_id'), 'skill_group', ['character_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_group_character_id'), table_name='skill_group')
    op.drop_table('skill_group')
    op.drop_index(op.f('ix_passive_tree_character_id'), table_name='passive_tree')
    op.drop_table('passive_tree')
    op.drop_table('generated_build')
    op.drop_index(op.f('ix_game_mechanic_skill_id'), table_name='game_mechanic')
    op.drop_table('game_mechanic')
    op.drop_index(op.f('ix_equipment_item_character_id'), table_name='equipment_item')
    op.drop_table('equipment_item')
    op.drop_index(op.f('ix_character_league'), table_name='character')
    op.drop_index(op.f('ix_character_character_name'), table_name='character')
    op.drop_index(op.f('ix_character_account_name'), table_name='character')
    op.drop_table('character')
    op.drop_index(op.f('ix_build_meta_character_id'), table_name='build_meta')
    op.drop_table('build_meta')
    # ### end Alembic commands ###
