"""change unique_item item_class from String(64) to Text

Revision ID: 8cdd9188c489
Revises: ac1336042f16
Create Date: 2026-05-22 23:33:27.333294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cdd9188c489'
down_revision: Union[str, Sequence[str], None] = 'ac1336042f16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unique_item', 'item_class',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_unique_item_item_class'), table_name='unique_item')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_unique_item_item_class'), 'unique_item', ['item_class'], unique=False)
    op.alter_column('unique_item', 'item_class',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###
