"""add_item_base_unique_modifier_passive_ascendancy

Revision ID: 916d79c0b459
Revises: 1e0e137c9b51
Create Date: 2026-05-22 21:46:02.024817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '916d79c0b459'
down_revision: Union[str, Sequence[str], None] = '1e0e137c9b51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ascendancy_class',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name_en', sa.String(length=128), nullable=False),
    sa.Column('name_zh', sa.String(length=128), nullable=True),
    sa.Column('base_class', sa.String(length=64), nullable=False),
    sa.Column('description_zh', sa.String(length=2048), nullable=True),
    sa.Column('node_gids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('game_version', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ascendancy_class_name_en'), 'ascendancy_class', ['name_en'], unique=False)
    op.create_table('item_base',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name_en', sa.String(length=256), nullable=False),
    sa.Column('name_zh', sa.String(length=256), nullable=True),
    sa.Column('item_class', sa.String(length=64), nullable=False),
    sa.Column('inventory_slots', sa.Integer(), nullable=True),
    sa.Column('drop_level', sa.Integer(), nullable=True),
    sa.Column('required_level', sa.Integer(), nullable=True),
    sa.Column('required_str', sa.Integer(), nullable=True),
    sa.Column('required_dex', sa.Integer(), nullable=True),
    sa.Column('required_int', sa.Integer(), nullable=True),
    sa.Column('implicit_mods', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('base_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weapon_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('game_version', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_base_item_class'), 'item_base', ['item_class'], unique=False)
    op.create_index(op.f('ix_item_base_name_en'), 'item_base', ['name_en'], unique=False)
    op.create_table('modifier',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stat_id', sa.String(length=128), nullable=False),
    sa.Column('name_en', sa.String(length=256), nullable=True),
    sa.Column('name_zh', sa.String(length=256), nullable=True),
    sa.Column('mod_type', sa.String(length=32), nullable=False),
    sa.Column('item_class_restrictions', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('spawn_weight', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stat_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('min_ilvl', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('game_version', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modifier_stat_id'), 'modifier', ['stat_id'], unique=False)
    op.create_table('passive_node',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_gid', sa.String(length=64), nullable=False),
    sa.Column('name_en', sa.String(length=256), nullable=True),
    sa.Column('name_zh', sa.String(length=256), nullable=True),
    sa.Column('node_type', sa.String(length=32), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('ascendancy_class', sa.String(length=64), nullable=True),
    sa.Column('connections', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('game_version', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passive_node_node_gid'), 'passive_node', ['node_gid'], unique=True)
    op.create_table('unique_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name_en', sa.String(length=256), nullable=False),
    sa.Column('name_zh', sa.String(length=256), nullable=True),
    sa.Column('base_item_type', sa.String(length=128), nullable=True),
    sa.Column('item_class', sa.String(length=64), nullable=True),
    sa.Column('required_level', sa.Integer(), nullable=True),
    sa.Column('required_str', sa.Integer(), nullable=True),
    sa.Column('required_dex', sa.Integer(), nullable=True),
    sa.Column('required_int', sa.Integer(), nullable=True),
    sa.Column('explicit_mods', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('flavour_text', sa.String(length=2048), nullable=True),
    sa.Column('is_boss_drop', sa.Boolean(), nullable=True),
    sa.Column('boss_source', sa.String(length=256), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('game_version', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unique_item_item_class'), 'unique_item', ['item_class'], unique=False)
    op.create_index(op.f('ix_unique_item_name_en'), 'unique_item', ['name_en'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unique_item_name_en'), table_name='unique_item')
    op.drop_index(op.f('ix_unique_item_item_class'), table_name='unique_item')
    op.drop_table('unique_item')
    op.drop_index(op.f('ix_passive_node_node_gid'), table_name='passive_node')
    op.drop_table('passive_node')
    op.drop_index(op.f('ix_modifier_stat_id'), table_name='modifier')
    op.drop_table('modifier')
    op.drop_index(op.f('ix_item_base_name_en'), table_name='item_base')
    op.drop_index(op.f('ix_item_base_item_class'), table_name='item_base')
    op.drop_table('item_base')
    op.drop_index(op.f('ix_ascendancy_class_name_en'), table_name='ascendancy_class')
    op.drop_table('ascendancy_class')
    # ### end Alembic commands ###
