"""add_content_hash_and_is_active_to_game_mechanic

Revision ID: ac1336042f16
Revises: 916d79c0b459
Create Date: 2026-05-22 21:54:06.880987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac1336042f16'
down_revision: Union[str, Sequence[str], None] = '916d79c0b459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('game_mechanic', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.add_column('game_mechanic', sa.Column('is_active', sa.Boolean(), nullable=True))
    # 现有记录全部标记为 active
    op.execute("UPDATE game_mechanic SET is_active = TRUE WHERE is_active IS NULL")
    op.alter_column('game_mechanic', 'is_active', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_mechanic', 'is_active')
    op.drop_column('game_mechanic', 'content_hash')
    # ### end Alembic commands ###
