"""add_cluster_jewel_base

Revision ID: efee3dc49049
Revises: 1c6c9a9614bb
Create Date: 2026-05-23 02:45:27.134307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efee3dc49049'
down_revision: Union[str, Sequence[str], None] = '1c6c9a9614bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_jewel_base',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name_en', sa.String(length=128), nullable=False),
    sa.Column('size', sa.String(length=16), nullable=False),
    sa.Column('size_index', sa.Integer(), nullable=True),
    sa.Column('min_nodes', sa.Integer(), nullable=True),
    sa.Column('max_nodes', sa.Integer(), nullable=True),
    sa.Column('small_indices', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('notable_indices', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('socket_indices', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('total_indices', sa.Integer(), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('game_version', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cluster_jewel_base_name_en'), 'cluster_jewel_base', ['name_en'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cluster_jewel_base_name_en'), table_name='cluster_jewel_base')
    op.drop_table('cluster_jewel_base')
    # ### end Alembic commands ###
